{{- if .Values.crd.create }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pravegaclusters.pravega.pravega.io
spec:
  group: pravega.pravega.io
  names:
    kind: PravegaCluster
    listKind: PravegaClusterList
    plural: pravegaclusters
    singular: pravegacluster
  additionalPrinterColumns:
  - name: Version
    type: string
    description: The current pravega version
    JSONPath: .status.currentVersion
  - name: Desired Version
    type: string
    description: The desired pravega version
    JSONPath: .spec.version
  - name: Desired Members
    type: integer
    description: The number of desired pravega members
    JSONPath: .status.replicas
  - name: Ready Members
    type: integer
    description: The number pravega members ready
    JSONPath: .status.readyReplicas
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              authentication:
                type: object
              bookkeeper:
                type: object
              externalAccess:
                type: string
              pravega:
                type: object
              tls:
                type: object
              version:
                type: string
              zookeeperUri:
                type: string
            type: object
          status:
            type: object
        type: object
        x-kubernetes-preserve-unknown-fields: true
  - name: v1beta1
    served: true
    storage: false
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              authentication:
                type: object
              bookkeeperUri:
                type: string
              externalAccess:
                type: string
              pravega:
                type: object
              tls:
                type: object
              version:
                type: string
              zookeeperUri:
                type: string
            type: object
          status:
            type: object
        type: object
        x-kubernetes-preserve-unknown-fields: true
  subresources:
    status: {}
{{- end }}
